Cleanup/main.py
Cobweb-Aclevo/minimal pull request #15
Opened 2021-06-18 14:18 UTC by ReasonablySelenium

Cleans up main.py and adds embeds/help.json to handle the help function.

2021-06-18 14:27 UTC, OfekShochat reviewed
what is that embeds/about.json file? seems to be empty.

2021-06-18 14:45 UTC, OfekShochat requested changes
please change that embeds/about.json file to be fitted to the `about` function in main.py. when that's met, this or will be merged. 
thank you for contributing,
Ofek

2021-06-20 10:01 UTC, OfekShochat commented
Thank you so much. Will look at it when at home!

2021-06-20 12:00 UTC, OfekShochat requested changes

2021-06-20 12:03 UTC, OfekShochat commented on main.py
> +        except SyntaxError as e:
also if you dont mind, send that to the discord chat instead of printing

2021-06-22 14:53 UTC, ReasonablySelenium commented on main.py
> +        except SyntaxError as e:
I made a change to the code. Please review.

2021-06-22 17:45 UTC, OfekShochat approved these changes

2021-06-22 17:46 UTC, merged

2021-06-22 17:46 UTC, OfekShochat commented
thank you for contributing to minimal